# Setup
title:               BRIDGEBLOG
tagline:             bridging nerdy stuff to pursue pleasant elegance
url:                 https://blog.defcesco.io
analytics_id:        

# About/contact
author:
  name:                Austin A. DeFrancesco
  email:               "austin[@]defcesco[.]io"
  avatar:              https://defcesco.io/assets/profile.jpg
  profile-pic:         https://defcesco.io/assets/profile.jpg

# SEO settings
twitter_username:    defcesco
github_username:     defcesco



# Build settings
markdown:            kramdown
permalink:           /:title
sass:
  sass_dir:          _sass
  style:            :compressed


# Default settings
defaults:
  -
    scope:
      path: "" 
      type: "posts" 
    values:
      layout: "post"
      author: Austin A. DeFrancesco
  -
    scope:
      path: "" 
      type: "pages" 
    values:
      layout: "page"

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
description:         Austin A. DeFrancesco's cybersecurity blog covering detection engineering, vulnerability research, and threat intelligence. Bridging nerdy stuff to pursue pleasant elegance.
